module.exports = {
  baseSourcePath: 'source',
  devDependencies: [
    '@babel/core',
    '@babel/plugin-proposal-decorators',
    '@types/faker',
    '@types/jest',
    'autoprefixer',
  ],
  devDependenciesSpecifics: {
    '@typescript-eslint/eslint-plugin': '4.32.0',
    '@commitlint/config-conventional': '13.2.0',
    '@typescript-eslint/parser': '4.32.0',
    cypress: '8.5.0',
    'env-cmd': '10.1.0',
    eslint: '7.32.0',
    'eslint-config-prettier': '8.3.0',
    'eslint-config-standard-with-typescript': '21.0.1',
    'eslint-plugin-import': '2.24.2',
    'eslint-plugin-jest': '24.5.0',
    'eslint-plugin-node': '11.1.0',
    'eslint-plugin-promise': '5.1.0',
    'eslint-plugin-react': '7.26.1',
    husky: '7.0.2',
    jest: '27.2.4',
    'jest-mock-extended': '2.0.4',
    'lint-staged': '11.1.2',
    postcss: 'latest',
    prettier: '2.4.1',
    'standard-version': '9.3.1',
    tailwindcss: 'latest',
    'ts-jest': '27.0.5',
    typescript: '4.4.3',
  },
};
