module.exports = {
  baseSourcePath: 'source',
  dependencies: [],
  devDependencies: [
    'dotenv',
    '@commitlint/config-conventional',
    'env-cmd',
    'standard-version',
  ],
  devDependenciesSpecifics: {
    cypress: '8.5.0',
    husky: '7.0.4',
    prettier: '2.4.1',
    typescript: '4.4.4',
    eslint: '7.32.0',
    "@vitest/coverage-c8": "0.24.3",
    "@vitest/ui": "0.24.2",
    "vitest": "0.24.1",
    '@babel/plugin-proposal-decorators': '7.17.2',
    '@babel/core': '7.17.5',
    '@typescript-eslint/eslint-plugin': '4.32.0',
    '@typescript-eslint/parser': '4.32.0',
    'eslint-config-prettier': '8.3.0',
    'eslint-config-standard-with-typescript': '21.0.1',
    'eslint-plugin-import': '2.25.2',
    'eslint-plugin-node': '11.1.0',
    'eslint-plugin-promise': '5.1.1',
    'eslint-plugin-react': '7.26.1',
    'lint-staged': '11.2.6',
  },
};
